# LOCAL HOST
# NOTE: REPLACE JWT WITH YOUR OWN GENERATED TOKENS RECEIVED AFTER A LOGIN PROCESS
# Authorization: Bearer <Your token>

# GET TO THE API DOCUMENTATION
###
http://localhost:3000/api-docs/#/

# LOGIN(AND / REGISTER) VIA OUTH GOOGLE
###
POST http://localhost:3000/users/google

# STANDARD LOGIN  
###
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "flibbit31@yahoo.com",
    "password":"#123456"
}

# STANDARD USER REGISTRATION 
###
POST http://localhost:3000/users/registerUser
Content-Type: application/json

{
    "firstName": "Benjamin",
    "lastName": "Beales",
    "email": "flibbit31@yahoo.com",
    "password":"#123456"
}

# USER UPDATE 
###
PUT http://localhost:3000/users/updateUser
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDA3MjY2MzEwN2Q1Njc3NTkzOGI2ZDgiLCJpYXQiOjE2NzgxOTAxNzksImV4cCI6MTY3ODI3NjU3OX0.rV7DX_45GgTuvW8L-1Q7ewpT8cQfhV4EDCDtK5LDjP8

{
    "firstName": "Danny",
    "lastName": "Kaya",
    "email": "DannyKaya@gmail.com",
    "birthday": "18-01-2020",
    "gender": "Male",
    "country": "Zambia"
}

# GET A SINGLE USER
###
GET http://localhost:3000/users/64072663107d56775938b6d8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDA3MjY2MzEwN2Q1Njc3NTkzOGI2ZDgiLCJpYXQiOjE2NzgxOTAxNzksImV4cCI6MTY3ODI3NjU3OX0.rV7DX_45GgTuvW8L-1Q7ewpT8cQfhV4EDCDtK5LDjP8

# GET ALL USERS
###
GET http://localhost:3000/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDA3MjY2MzEwN2Q1Njc3NTkzOGI2ZDgiLCJpYXQiOjE2NzgxOTAxNzksImV4cCI6MTY3ODI3NjU3OX0.rV7DX_45GgTuvW8L-1Q7ewpT8cQfhV4EDCDtK5LDjP8

# HOUSE ROUTES
# ADDING A HOUSE 
###
POST http://localhost:3000/houses/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDE0NjRmZDkyNTMyYmRiMzI3ZjdmNmIiLCJpYXQiOjE2NzkwNTgxOTEsImV4cCI6MTY3OTE0NDU5MX0.s-HayWFawHNK13TCnxfEUiaYcguSiVDpuAIIhGHk1GM

{
    "price": "10000",
    "houseNumber": "12345",
    "streetName": "tusha street",
    "residentialAreaName":"North rise",
    "city": "ndola",
    "province": "Copperbelt",
    "country": "Zambia",
    "minimumStayMonths":"2 months",
    "maximumStayMonths": "two years",
    "description": "Amazing house, very comfy!",
    "viewingTimePeriod": "9hrs to 12hrs",
    "landlordEmail":"simycodes@gmail.com",
    "landlordPhoneNumber": "260974372761",
    "images": []
}

# UPDATING A HOUSE 
###
PUT http://localhost:3000/houses/64146ddcfb2dd030accd6829
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDE0NjRmZDkyNTMyYmRiMzI3ZjdmNmIiLCJpYXQiOjE2NzkwNTgxOTEsImV4cCI6MTY3OTE0NDU5MX0.s-HayWFawHNK13TCnxfEUiaYcguSiVDpuAIIhGHk1GM

{
    "price": "10000-edited",
    "houseNumber": "12345",
    "streetName": "tusha street",
    "residentialAreaName":"North rise",
    "city": "ndola",
    "province": "Copperbelt",
    "country": "Zambia",
    "minimumStayMonths":"2 months",
    "maximumStayMonths": "two years",
    "description": "Amazing house, very comfy!",
    "viewingTimePeriod": "9hrs to 12hrs",
    "landlordEmail":"simycodes@gmail.com",
    "landlordPhoneNumber": "+260974372761",
    "images": []
}

# GET A SINGLE HOUSE
###
GET http://localhost:3000/houses/64146725465d2b405da036c5


# GET ALL HOUSES
###
GET http://localhost:3000/houses

# DELETE A HOUSE
###
DELETE http://localhost:3000/houses/6414697a0ca3402a98ef5504
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDE0NjRmZDkyNTMyYmRiMzI3ZjdmNmIiLCJpYXQiOjE2NzkwNTgxOTEsImV4cCI6MTY3OTE0NDU5MX0.s-HayWFawHNK13TCnxfEUiaYcguSiVDpuAIIhGHk1GM

# APARTMENTS ROUTES
# ADDING AN APARTMENT 
###
POST http://localhost:3000/apartments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDFkOGFmNmU1ZGRiZGZhNTg3NGM0ODYiLCJpYXQiOjE2Nzk2NTc3MTgsImV4cCI6MTY3OTc0NDExOH0.T68bt7UXIe3WppS9HcqbH0B6lWL52ghMMO2kzLWN7yI

{
    "price": "100",
    "rentalType": "Shared",
    "apartmentPlotNumber": "1234",
    "houseNumber": "12345",
    "streetName": "tusha street",
    "ApartmentBuildingName": "Simy Flats",
    "residentialAreaName":"North rise",
    "city": "ndola",
    "province": "Copperbelt",
    "country": "Zambia",
    "minimumStayMonths":"2 months",
    "maximumStayMonths": "two years",
    "description": "Amazing house, very comfy!",
    "viewingTimePeriod": "9hrs to 12hrs",
    "landlordEmail":"simycodes@gmail.com",
    "landlordPhoneNumber": "260974372761",
    "images": []
}

# UPDATING AN APARTMENT 
###
PUT http://localhost:3000/apartments/641477268dec571490411cfc
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDE0NjRmZDkyNTMyYmRiMzI3ZjdmNmIiLCJpYXQiOjE2NzkwNTgxOTEsImV4cCI6MTY3OTE0NDU5MX0.s-HayWFawHNK13TCnxfEUiaYcguSiVDpuAIIhGHk1GM

{
    "price": "100-updated",
    "rentalType": "Shared",
    "apartmentPlotNumber": "1234",
    "houseNumber": "12345",
    "streetName": "tusha street",
    "ApartmentBuildingName": "Simy Flats",
    "residentialAreaName":"North rise",
    "city": "ndola",
    "province": "Copperbelt",
    "country": "Zambia",
    "minimumStayMonths":"2 months",
    "maximumStayMonths": "two years",
    "description": "Amazing house, very comfy!",
    "viewingTimePeriod": "9hrs to 12hrs",
    "landlordEmail":"simycodes@gmail.com",
    "landlordPhoneNumber": "260974372761",
    "images": []
}

# GET A SINGLE APARTMENT
###
GET http://localhost:3000/apartments/6414771b8dec571490411cf8


# GET ALL APARTMENTS
###
GET http://localhost:3000/apartments

# DELETE AN APARTMENT
###
DELETE http://localhost:3000/apartments/641476fc8dec571490411cf0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDE0NjRmZDkyNTMyYmRiMzI3ZjdmNmIiLCJpYXQiOjE2NzkwNTgxOTEsImV4cCI6MTY3OTE0NDU5MX0.s-HayWFawHNK13TCnxfEUiaYcguSiVDpuAIIhGHk1GM

# APPOINTMENTS ROUTES
# ADDING AN APPOINTMENT
###
POST http://localhost:3000/appointments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDFkOGFmNmU1ZGRiZGZhNTg3NGM0ODYiLCJpYXQiOjE2Nzk2NTc3MTgsImV4cCI6MTY3OTc0NDExOH0.T68bt7UXIe3WppS9HcqbH0B6lWL52ghMMO2kzLWN7yI

{
    "dateAndTime": "2023-07-07T08:00:00",
    "houseOrApartmentId": "641d8beae5ddbdfa5874c488"
}

# UPDATING AN APPOINTMENT
###
PUT http://localhost:3000/appointments/641d98a20cbfb3e5788d4c95
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDFkOGFmNmU1ZGRiZGZhNTg3NGM0ODYiLCJpYXQiOjE2Nzk2NTc3MTgsImV4cCI6MTY3OTc0NDExOH0.T68bt7UXIe3WppS9HcqbH0B6lWL52ghMMO2kzLWN7yI

{
    "dateAndTime": "2023-08-04T08:00:00",
    "houseOrApartmentId": "641d8beae5ddbdfa5874c488"
}

# GET A SINGLE APPOINTMENT
###
GET http://localhost:3000/appointments/641d98a20cbfb3e5788d4c95
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDFkOGFmNmU1ZGRiZGZhNTg3NGM0ODYiLCJpYXQiOjE2Nzk2NTc3MTgsImV4cCI6MTY3OTc0NDExOH0.T68bt7UXIe3WppS9HcqbH0B6lWL52ghMMO2kzLWN7yI

# GET ALL APPOINTMENTS
###
GET http://localhost:3000/appointments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDFkOGFmNmU1ZGRiZGZhNTg3NGM0ODYiLCJpYXQiOjE2Nzk2NTc3MTgsImV4cCI6MTY3OTc0NDExOH0.T68bt7UXIe3WppS9HcqbH0B6lWL52ghMMO2kzLWN7yI

# DELETE AN APPOINTMENT
###
DELETE http://localhost:3000/appointments/641d98a20cbfb3e5788d4c95
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDFkOGFmNmU1ZGRiZGZhNTg3NGM0ODYiLCJpYXQiOjE2Nzk2NTc3MTgsImV4cCI6MTY3OTc0NDExOH0.T68bt7UXIe3WppS9HcqbH0B6lWL52ghMMO2kzLWN7yI

# DISPLAY AND INTERACT WITH THE CONTACTS API DOCUMENTATION - USE BROWSER FOR THIS ROUTE
#ON RENDER
###
https://cse341-rental-api-service.onrender.com/api-docs/#/

# LOGIN VIA OUTH GOOGLE
###
POST https://cse341-rental-api-service.onrender.com/users/google

# STANDARD LOGIN  
###
POST https://cse341-rental-api-service.onrender.com/users/login
Content-Type: application/json

{
    "email": "john@gmail.com",
    "password":"1234567"
}



#ON RENDER
# STANDARD USER REGISTRATION 
###
POST https://cse341-rental-api-service.onrender.com/users/registerUser
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Peter",
    "email": "john@gmail.com",
    "password": "123456"
}

# USER UPDATE 
###
PUT https://cse341-rental-api-service.onrender.com/users/updateUser
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2Y5MGRmMDQ3NDRjY2UxMGYzZDY2MmEiLCJpYXQiOjE2NzczNDMzMTksImV4cCI6MTY3NzQyOTcxOX0.x1lxi_u0OKKmyu6ahjJDw_fEiyBWI1iH0Ai5Uxz-9AY

{
    "firstName": "Bwalya",
    "lastName": "Mutondo",
    "email": "bwalya1234@gmail.com",
    "password":"123456",
    "birthday": "18-05-200",
    "gender": "male",
    "country": "Zambia"
}

# GET A SINGLE USER
###
GET https://cse341-rental-api-service.onrender.com/users/63dd05a9876d194ec8741694
Authorization: Bearer

# GET ALL USERS
###
GET https://cse341-rental-api-service.onrender.com/users/
Authorization: Bearer

# HOUSE ROUTES
# ADDING A HOUSE 
###
POST https://cse341-rental-api-service.onrender.com/houses/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDE0NjRmZDkyNTMyYmRiMzI3ZjdmNmIiLCJpYXQiOjE2NzkwNTgxOTEsImV4cCI6MTY3OTE0NDU5MX0.s-HayWFawHNK13TCnxfEUiaYcguSiVDpuAIIhGHk1GM

{
    "price": "10000",
    "houseNumber": "12345",
    "streetName": "tusha street",
    "residentialAreaName":"North rise",
    "city": "ndola",
    "province": "Copperbelt",
    "country": "Zambia",
    "minimumStayMonths":"2 months",
    "maximumStayMonths": "two years",
    "description": "Amazing house, very comfy!",
    "viewingTimePeriod": "9hrs to 12hrs",
    "landlordEmail":"simycodes@gmail.com",
    "landlordPhoneNumber": "260974372761",
    "images": []
}

# UPDATING A HOUSE 
###
PUT https://cse341-rental-api-service.onrender.com/houses/64146ddcfb2dd030accd6829
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDE0NjRmZDkyNTMyYmRiMzI3ZjdmNmIiLCJpYXQiOjE2NzkwNTgxOTEsImV4cCI6MTY3OTE0NDU5MX0.s-HayWFawHNK13TCnxfEUiaYcguSiVDpuAIIhGHk1GM

{
    "price": "10000-edited",
    "houseNumber": "12345",
    "streetName": "tusha street",
    "residentialAreaName":"North rise",
    "city": "ndola",
    "province": "Copperbelt",
    "country": "Zambia",
    "minimumStayMonths":"2 months",
    "maximumStayMonths": "two years",
    "description": "Amazing house, very comfy!",
    "viewingTimePeriod": "9hrs to 12hrs",
    "landlordEmail":"simycodes@gmail.com",
    "landlordPhoneNumber": "+260974372761",
    "images": []
}

# GET A SINGLE HOUSE
###
GET https://cse341-rental-api-service.onrender.com/houses/64146725465d2b405da036c5


# GET ALL HOUSES
###
GET https://cse341-rental-api-service.onrender.com/houses

# DELETE A HOUSE
###
DELETE https://cse341-rental-api-service.onrender.com/houses/6414697a0ca3402a98ef5504
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDE0NjRmZDkyNTMyYmRiMzI3ZjdmNmIiLCJpYXQiOjE2NzkwNTgxOTEsImV4cCI6MTY3OTE0NDU5MX0.s-HayWFawHNK13TCnxfEUiaYcguSiVDpuAIIhGHk1GM

# APARTMENTS ROUTES
# ADDING AN APARTMENT 
###
POST https://cse341-rental-api-service.onrender.com/apartments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDE0NjRmZDkyNTMyYmRiMzI3ZjdmNmIiLCJpYXQiOjE2NzkwNTgxOTEsImV4cCI6MTY3OTE0NDU5MX0.s-HayWFawHNK13TCnxfEUiaYcguSiVDpuAIIhGHk1GM

{
    "price": "100",
    "rentalType": "Shared",
    "apartmentPlotNumber": "1234",
    "houseNumber": "12345",
    "streetName": "tusha street",
    "ApartmentBuildingName": "Simy Flats",
    "residentialAreaName":"North rise",
    "city": "ndola",
    "province": "Copperbelt",
    "country": "Zambia",
    "minimumStayMonths":"2 months",
    "maximumStayMonths": "two years",
    "description": "Amazing house, very comfy!",
    "viewingTimePeriod": "9hrs to 12hrs",
    "landlordEmail":"simycodes@gmail.com",
    "landlordPhoneNumber": "260974372761",
    "images": []
}

# UPDATING AN APARTMENT 
###
PUT https://cse341-rental-api-service.onrender.com/apartments/641477268dec571490411cfc
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDE0NjRmZDkyNTMyYmRiMzI3ZjdmNmIiLCJpYXQiOjE2NzkwNTgxOTEsImV4cCI6MTY3OTE0NDU5MX0.s-HayWFawHNK13TCnxfEUiaYcguSiVDpuAIIhGHk1GM

{
    "price": "100-updated",
    "rentalType": "Shared",
    "apartmentPlotNumber": "1234",
    "houseNumber": "12345",
    "streetName": "tusha street",
    "ApartmentBuildingName": "Simy Flats",
    "residentialAreaName":"North rise",
    "city": "ndola",
    "province": "Copperbelt",
    "country": "Zambia",
    "minimumStayMonths":"2 months",
    "maximumStayMonths": "two years",
    "description": "Amazing house, very comfy!",
    "viewingTimePeriod": "9hrs to 12hrs",
    "landlordEmail":"simycodes@gmail.com",
    "landlordPhoneNumber": "260974372761",
    "images": []
}

# GET A SINGLE APARTMENT
###
GET https://cse341-rental-api-service.onrender.com/apartments/6414771b8dec571490411cf8


# GET ALL APARTMENTS
###
GET https://cse341-rental-api-service.onrender.com/apartments

# DELETE AN APARTMENT
###
DELETE https://cse341-rental-api-service.onrender.com/apartments/641476fc8dec571490411cf0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDE0NjRmZDkyNTMyYmRiMzI3ZjdmNmIiLCJpYXQiOjE2NzkwNTgxOTEsImV4cCI6MTY3OTE0NDU5MX0.s-HayWFawHNK13TCnxfEUiaYcguSiVDpuAIIhGHk1GM

